name: CI/CD
permissions:
  contents: read

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v6
    - name: Install pnpm
      uses: pnpm/action-setup@v6
    - name: Use Node.js 22
      uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: 'pnpm'
    - name: Install, build, and test
      run: pnpm run ci
      env:
        CI: "true"
    - uses: actions/upload-artifact@v7
      with: 
        name: artifacts
        path: remote-kubernetes-*.vsix
