name: publish-marketplace
permissions:
  contents: read
on:
  release:
    types: 
    - published
    - edited

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v6
    - name: Install pnpm
      uses: pnpm/action-setup@v6
    - name: Use Node.js 22
      uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: 'pnpm'
    - run: pnpm run ci
    - name: publish
      if: github.event.release.prerelease != true
      run: pnpm run publish
      env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
    - name: publish-prerelease
      if: github.event.release.prerelease == true
      run: pnpm run publish-prerelease
      env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
