name: publish-marketplace
permissions:
  contents: read
on:
  release:
    types: 
    - published
    - edited

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v6
    - name: get tag
      id: vars
      run: echo "release_tag=$(echo ${GITHUB_REF:11})" > $GITHUB_ENV
    - name: Install pnpm
      uses: pnpm/action-setup@v6
    - name: Use Node.js 22
      uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: 'pnpm'
    - run: pnpm run ci
    - name: publish
      if: github.event.release.prerelease != true
      run: pnpm run publish
      env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
    - name: publish-prerelease
      if: github.event.release.prerelease == true
      run: pnpm run publish-prerelease
      env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
    - run: pnpm run publish-sentry 
      env:
          VERSION: remote-kubernetes-code@${{ env.release_tag }}
          SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
          SENTRY_ORG: okteto-analytics
          SENTRY_PROJECT: remote-kubernetes-vscode